# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Import Android orb
orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      # ✅ Fix permission denied error
      - run:
          name: Give gradlew execute permission
          command: chmod +x ./gradlew

      # Run lint and unit testsa
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      # Start emulator and run instrumentation tests
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      # Build the release APK
      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease

workflows:
  sample:
    jobs:
      - build-and-test
