version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "settings.gradle.kts" }}
            - gradle-cache-

      - run:
          name: Give gradlew execute permission
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - run:
          name: Run Lint & Unit Test
          command: ./gradlew lint testDebug --continue

      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk

      - store_test_results:
          path: app/build/test-results

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "settings.gradle.kts" }}

workflows:
  build:
    jobs:
      - build-and-test
